package br.com.fiap.fordvinshare.security.audit;

public enum AuditAction {
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	REGISTER,
	REFRESH_SUCCESS,
	REFRESH_REPLAY_DETECTED,
	LOGOUT,
	REVOKE_ALL,

	CLIENTE_CREATE,
	CLIENTE_UPDATE,
	CLIENTE_DELETE,
	VEICULO_CREATE,
	VEICULO_UPDATE,
	VEICULO_DELETE,
	MANUTENCAO_CREATE,
	MANUTENCAO_DELETE,
	LEAD_CREATE_MANUAL,
	LEAD_CREATE_AUTO,
	LEAD_STATUS_UPDATE
}
